on:
  workflow_dispatch: {}
  pull_request: {}
jobs:
  call-workflow-passing-data:
    uses: TestOrgForSemgrep/reusable_workflow_test/.github/workflows/reusable-semgrep.yml@main
    secrets:
      token: ${{ secrets.SEMGREP_ORG_TOKEN }}
