on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
jobs:
  call-workflow-passing-data:
    uses: TestOrgForSemgrep/reusable_workflow_test/.github/workflows/reusable-semgrep.yml@main
